name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - system: windows
          arch: i686
          icon: '⬛'
        - system: windows
          arch: x86_64
          icon: '🟦'
        - system: archlinux
          arch: x86_64
          icon: '🟦'

    name: 🚧${{ matrix.icon }} ${{ matrix.system }} (${{ matrix.arch }})
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run container
      if: contains(matrix.system, 'windows')
      uses: ./.github/actions/windows
      with:
        architecture: ${{ matrix.arch }}

    - name: Run container
      if: contains(matrix.system, 'archlinux')
      uses: ./.github/actions/archlinux

    - name: Uploading artifact for ${{ matrix.system }}-${{ matrix.arch }}
      if: contains(matrix.system, 'windows')
      uses: actions/upload-artifact@v2
      with:
        name: xava-installer-${{ matrix.arch }}.exe
        path: xava-installer-${{ matrix.arch }}.exe

    - name: Get Git info and share it globally
      if: contains(matrix.system, 'archlinux')
      id: vars
      run: |
        cd build
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

    - name: Upload AppImage artifact
      if: contains(matrix.system, 'archlinux')
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: xava-x86_64.AppImage
        path: build/xava-x86_64.AppImage

    - name: Upload version artifact
      if: contains(matrix.system, 'archlinux')
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: version.txt
        path: build/version.txt

